name: Download built package from cache
description: Download built package from cache
runs:
  using: "composite"
  steps:
  - name: Download built package from cache
    uses: actions/download-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
  - name: 'Install dependencies'
    shell: 'bash'
    # Handle issue where pnpm does not re-sync dependencies
    # when using dependenciesMeta.*.injected: true
    #
    # For more information see:
    #  - https://github.com/pnpm/pnpm/issues/4965
    #  - Possible solution: https://github.com/pnpm/pnpm/issues/4965#issuecomment-1405264290
    #  - Related issues:
    #    - https://github.com/pnpm/pnpm/issues/4625
    #    - https://github.com/pnpm/pnpm/issues/4988
    #    - https://github.com/pnpm/pnpm/issues/4625
    #    - https://github.com/pnpm/pnpm/issues/6002
    run: pnpm install --force
