name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect

# This task also uploads the built assets to a per-ci-run cache, so that
# we can be certain there is no flaky build behavior between the ci jobs
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    # This isn't meant to assert all files exist,
    # but is intended to make sure nothing catestrophic happens with the build
    # or would negatively affect consumers once published.
    # We require:
    #  - js maps
    #  - declaration files
    #  - declaration maps (these don't occur on all files)
    run: |-
      echo '
        target: ${{ env.dist }}
        setup:
          run: pnpm build
          cwd: ./ember-headless-form
        expect: |
          index.js
          index.js.map
          index.d.ts
          template-registry.js
          template-registry.js.map
          template-registry.d.ts
          components/-private/capture-events.d.ts
          components/-private/capture-events.d.ts.map

      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
